module.exports.HOST = process.env.HOST || 'localhost';
module.exports.ADMIN_PORT = process.env.ADMIN_PORT;
module.exports.API_PORT = process.env.API_PORT;
module.exports.EMAIL_SERVICE = process.env.EMAIL_SERVICE;
module.exports.EMAIL_AUTH = process.env.EMAIL_AUTH;
module.exports.EMAIL_PASSWORD = process.env.EMAIL_PASSWORD;
module.exports.FROM_EMAIL = process.env.FROM_EMAIL;
module.exports.DB_PATH = process.env.DB;
module.exports.MYSQL_HOST = process.env.MYSQL_HOST;
module.exports.MYSQL_USERNAME = process.env.MYSQL_USERNAME;
module.exports.MYSQL_PASSWORD = process.env.MYSQL_PASSWORD;
module.exports.MYSQL_DATABASE = process.env.MYSQL_DATABASE;
module.exports.DB_SELECT = process.env.DB_SELECT || 'json'
module.exports.ADMIN_PREFIX ='/admin';
